#ifndef __LWIPBSPOPTS_H__
#define __LWIPBSPOPTS_H__

#define CHECKSUM_BY_HARDWARE 0
#define ETH_RX_BUFFER_SIZE 1536
#define MEM_SIZE (256 * 1024)
#define PBUF_POOL_SIZE 64

#define LWIP_DEBUG 1
#define IP_DEBUG LWIP_DBG_ON
#define ETHARP_DEBUG LWIP_DBG_ON
#define ICMP_DEBUG LWIP_DBG_ON
#define UDP_DEBUG LWIP_DBG_ON
#define TCP_DEBUG LWIP_DBG_ON

#define LWIP_ICMP 1

#endif /* __LWIPBSPOPTS_H__ */
